# Prometheus Helm Chart Values

rbac:
  create: true

serviceAccounts:
  server:
    create: false
    name: prometheus

podSecurityPolicy:
  enabled: false

configmapReload:
  prometheus:
    enabled: true
    name: configmap-reload
    image:
      repository: jimmidyson/configmap-reload
      tag: v0.8.0
      pullPolicy: IfNotPresent

server:
  name: server

  image:
    repository: quay.io/prometheus/prometheus
    tag: v2.30.0
    pullPolicy: IfNotPresent

  ## Server container arguments
  extraFlags:
    - --web.enable-lifecycle

  ## Path to configuration file
  configPath: /etc/config/prometheus.yml

  global:
    scrape_interval: 1m
    scrape_timeout: 10s
    evaluation_interval: 1m

  remoteWrite: []
  remoteRead: []

  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    mountPath: /data

  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1024Mi
      cpu: 1

  service:
    enabled: true
    type: ClusterIP
    servicePort: 9090

  ingress:
    enabled: false

  ## Security settings
  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    fsGroup: 65534

alertmanager:
  enabled: true
  persistence:
    enabled: true
    size: 2Gi

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

  rbac:
    create: true
    pspEnabled: false

  containerSecurityContext:
    allowPrivilegeEscalation: false

prometheus-pushgateway:
  enabled: true
  service:
    annotations:
      prometheus.io/probe: pushgateway
